export const EMPRESA = {
  nome: "Oficina Ideal Jairo",
  fantasia: "Ideal Jairo — Mecânica Automotiva",
  cnpj: "58.623.937/0001-01",
  endereco: "R. Vicente Ítalo Feola, 560",
  bairro: "Cidade Ocian",
  cidade: "Praia Grande/SP",
  cep: "11704-230",
  telefone: "(13) 98867-3809",
  responsavelTecnico: "Jairo Alves de Oliveira",
  instagram: "https://www.instagram.com/mecanica_jairopg",
  garantiaPadraoDias: 90,
  textoGarantia:
    "Garantia de 90 dias aplicável somente às peças fornecidas pela oficina. O consumidor tem direito à garantia legal de 90 dias, conforme art. 26 do Código de Defesa do Consumidor.",
} as const;

export const ITENS_VISTORIA = [
  "Lataria Frontal",
  "Lataria Traseira",
  "Lat. Esquerda",
  "Lat. Direita",
  "Teto/Capota",
  "Para-brisa",
  "Vidro Traseiro",
  "Vidros Laterais",
  "Pneu D.E.",
  "Pneu D.D.",
  "Pneu T.E.",
  "Pneu T.D.",
  "Palhetas",
  "Ar Condicionado",
  "Luzes de Painel",
  "Piscas/Setas",
  "Freios",
  "Vazamentos",
  "Faróis Dianteiros",
  "Lanternas Traseiras",
  "Retrovisores",
  "Buzina",
] as const;

export const OPCOES_POR_ITEM: Record<string, readonly string[]> = {
  "Lataria Frontal":    ["OK", "Arranhado", "Amassado", "Danificado"],
  "Lataria Traseira":   ["OK", "Arranhado", "Amassado", "Danificado"],
  "Lat. Esquerda":      ["OK", "Arranhado", "Amassado", "Danificado"],
  "Lat. Direita":       ["OK", "Arranhado", "Amassado", "Danificado"],
  "Teto/Capota":        ["OK", "Arranhado", "Amassado", "Danificado"],
  "Para-brisa":         ["OK", "Trincas", "Danificado"],
  "Vidro Traseiro":     ["OK", "Trincas", "Danificado"],
  "Vidros Laterais":    ["OK", "Trincas", "Danificado"],
  "Pneu D.E.":          ["Bom", "Gasto", "Danificado"],
  "Pneu D.D.":          ["Bom", "Gasto", "Danificado"],
  "Pneu T.E.":          ["Bom", "Gasto", "Danificado"],
  "Pneu T.D.":          ["Bom", "Gasto", "Danificado"],
  "Palhetas":           ["OK", "Gastas", "Ressecadas", "Danificadas"],
  "Ar Condicionado":    ["OK", "Não funciona", "Não possui"],
  "Luzes de Painel":    ["OK", "Com alertas"],
  "Piscas/Setas":       ["OK", "Avariados", "Faltando"],
  "Freios":             ["OK", "Desgastados", "Ruins"],
  "Vazamentos":         ["Não", "Sim"],
  "Faróis Dianteiros":  ["OK", "Opacos", "Danificados"],
  "Lanternas Traseiras":["OK", "Opacas", "Danificadas"],
  "Retrovisores":       ["OK", "Arranhões", "Faltando", "Trincas", "Danificados"],
  "Buzina":             ["OK", "Com falhas"],
};

export const NIVEIS_COMBUSTIVEL = [
  "Reserva",
  "1/4 (25%)",
  "1/2 (50%)",
  "3/4 (75%)",
  "Cheio (100%)",
] as const;

export const OPCOES_VISTORIA = [
  "OK",
  "Arranhado",
  "Amassado",
  "Danificado",
  "Trincas",
  "Bom",
  "Gasto",
  "Gastas",
  "Ressecadas",
  "Danificadas",
  "Não funciona",
  "Não possui",
  "Com alertas",
  "Avariados",
  "Faltando",
  "Desgastados",
  "Ruins",
  "Sim",
  "Não",
  "Opacos",
  "Opacas",
  "Arranhões",
  "Com falhas",
] as const;

export const ITENS_INTERNOS = [
  "Documentos do Veículo",
  "Estepe",
  "Chave de Roda",
  "Kit de Primeiros Socorros",
  "Tapetes",
  "Chave Reserva",
  "Código do Rádio",
  "Extintor de Incêndio",
  "Macaco",
  "Triângulo de Sinalização",
  "Kit de Ferramentas",
  "Parasol (Protetor Solar)",
  "Manual do Proprietário",
] as const;
