/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as OsRouteImport } from './routes/os'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as ApiGerarPdfRouteImport } from './routes/api/gerar-pdf'
import { Route as OsIdRouteImport } from './routes/os_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGerarPdfRoute = ApiGerarPdfRouteImport.update({
  id: '/api/gerar-pdf',
  path: '/api/gerar-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIdRoute = OsIdRouteImport.update({
  id: '/os_/$id',
  path: '/os/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/os': typeof OsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/gerar-pdf': typeof ApiGerarPdfRoute
  '/os/$id': typeof OsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/os': typeof OsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/gerar-pdf': typeof ApiGerarPdfRoute
  '/os/$id': typeof OsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/orcamentos': typeof OrcamentosRoute
  '/os': typeof OsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/api/gerar-pdf': typeof ApiGerarPdfRoute
  '/os_/$id': typeof OsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/orcamentos'
    | '/os'
    | '/privacidade'
    | '/relatorios'
    | '/termos'
    | '/usuarios'
    | '/veiculos'
    | '/api/gerar-pdf'
    | '/os/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/orcamentos'
    | '/os'
    | '/privacidade'
    | '/relatorios'
    | '/termos'
    | '/usuarios'
    | '/veiculos'
    | '/api/gerar-pdf'
    | '/os/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/orcamentos'
    | '/os'
    | '/privacidade'
    | '/relatorios'
    | '/termos'
    | '/usuarios'
    | '/veiculos'
    | '/api/gerar-pdf'
    | '/os_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendarRoute: typeof AgendarRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  OrcamentosRoute: typeof OrcamentosRoute
  OsRoute: typeof OsRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TermosRoute: typeof TermosRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  ApiGerarPdfRoute: typeof ApiGerarPdfRoute
  OsIdRoute: typeof OsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gerar-pdf': {
      id: '/api/gerar-pdf'
      path: '/api/gerar-pdf'
      fullPath: '/api/gerar-pdf'
      preLoaderRoute: typeof ApiGerarPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os_/$id': {
      id: '/os_/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof OsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendarRoute: AgendarRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  OrcamentosRoute: OrcamentosRoute,
  OsRoute: OsRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatoriosRoute: RelatoriosRoute,
  TermosRoute: TermosRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  ApiGerarPdfRoute: ApiGerarPdfRoute,
  OsIdRoute: OsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
